- name: cart component
  hosts: cart
  become: yes
  tasks:
  - name: Disable old nodejs and enable new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: Create a roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download cart application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: Extract cart application in cart app directory
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies # Change the directory to app
    ansible.builtin.command: npm install
    args:
      chdir: /app
  
  - name: create cart service # we have already had a cart.service file in repostiry , hence copying to actual path.
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: Just force systemd to reread configs
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: Start and enable the cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes