- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable old nodejs and enable new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: Create a roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Extract catalogue application in catalogue app directory
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies # Change the directory to app
    ansible.builtin.command: npm install
    args:
      chdir: /app
  
  - name: create catalogue service # we have already had a catalogue.service file in repostiry , hence copying to actual path.
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Just force systemd to reread configs
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: setup MongoDB repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb-client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: Get the catageries count
    ansible.builtin.command: mongo --host mongodb.dhanaskanda.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "Product count: {{product_count}}"

  - name: Load the catalogue data
    ansible.builtin.command: mongo --host mongodb.dhanaskanda.online < /app/schema/catalogue.js
    when: product_count.stdout == "0" 

  - name: Start and enable the catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes

  