- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable old nodejs and enable new nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: Create a roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Extract catalogue application in catalogue app directory
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies # Change the directory to app
    ansible.builtin.command: npm install
    args:
      chdir: /app
  
  - name: create catalogue service # we have already had a catalogue.service file in repostiry , hence copying to actual path.
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

