- name: user
  hosts: user
  tasks:
    - name: Disable and enable nodejs
      ansibile.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create roboshop user
      ansibile.builtin.user:
        name: roboshop

    - name: create a app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the user application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp
      
    - name: Extract the user application into app directory
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: Install the dependenices
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: setup systemD user service # user.service file already created in this location.
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: setup MongoDB repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install the mongodb client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present

    - name: Get the user count
      ansible.builtin.command: mongo --host mongodb.dhanaskanda.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
      register: user_count

    - name: Print the user count
      ansible.builtin.debug:
        msg: "User count: {{user_count}}"

    - name: Load the user data
      ansible.builtin.command: mongo --host mongodb.dhanaskanda.online < /app/schema/user.js
      when: user_count == "0"

    - name: Start and enable the user
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes