- name: web component
  hosts: web
  tasks:
  - name: Install nginx 
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Remove the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create a html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download web content
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: extract the web conent
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /app
      remote_src: yes

  - name: copy the roboshop configuration
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: Start and enable the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes
  